import bug from "../assets/teraType/bug.png";
import normal from "../assets/teraType/normal.png";
import fire from "../assets/teraType/fire.png";
import water from "../assets/teraType/water.png";
import electric from "../assets/teraType/electric.png";
import grass from "../assets/teraType/grass.png";
import ice from "../assets/teraType/ice.png";
import fighting from "../assets/teraType/fighting.png";
import poison from "../assets/teraType/poison.png";
import ground from "../assets/teraType/ground.png";
import flying from "../assets/teraType/flying.png";
import psychic from "../assets/teraType/psychic.png";
import rock from "../assets/teraType/rock.png";
import ghost from "../assets/teraType/ghost.png";
import dragon from "../assets/teraType/dragon.png";
import dark from "../assets/teraType/dark.png";
import steel from "../assets/teraType/steel.png";
import fairy from "../assets/teraType/fairy.png";

export const teratypeImage = (type: string) => {
  if (type === "bug") return bug;
  if (type === "fire") return fire;
  if (type === "water") return water;
  if (type === "electric") return electric;
  if (type === "grass") return grass;
  if (type === "ice") return ice;
  if (type === "fighting") return fighting;
  if (type === "poison") return poison;
  if (type === "ground") return ground;
  if (type === "flying") return flying;
  if (type === "psychic") return psychic;
  if (type === "rock") return rock;
  if (type === "ghost") return ghost;
  if (type === "dragon") return dragon;
  if (type === "dark") return dark;
  if (type === "steel") return steel;
  if (type === "fairy") return fairy;
  return normal;
};
